#!/bin/bash

# Edit path to your root setup
#source /opt/soft/root/v6.14.06/root/bin/thisroot.sh

export JSNS2_HOME=${PWD}
export PATH=${PWD}/bin:${PATH}
export LD_LIBRARY_PATH=${PWD}/lib:${LIBPATH}
export LIBPATH=${PWD}/lib:${LIBPATH}

# Edit path to EPICS-base for runcontrol package
export EPICS_HOME=/home/tkonno/epics-base
export PATH=${EPICS_HOME}/bin/linux-x86_64:${PATH}
