#!/bin/bash

if [ ! -e /opt/gcc-4.8.5/bin/gcc ]; then
    # Edit path to your root setup
    if [ -e /opt/soft/root/v6.14.06/bin/thisroot.sh ]; then
	source /opt/soft/root/v6.14.06/bin/thisroot.sh
    fi
else
    ## setting enviroment variables in KEKCC
    module load gcc/485
    module load python/2.7
    export PATH=/sw/packages/cmake3/bin:${PATH}
    source /sw/packages/root/6.16.00/bin/thisroot.sh
fi

export JSNS2_HOME=${PWD}
export PATH=${PWD}/bin:${PATH}
export LD_LIBRARY_PATH=${PWD}/lib:${LIBPATH}
export LIBPATH=${PWD}/lib:${LIBPATH}

# Edit path to EPICS-base for runcontrol package
export EPICS_HOME=/home/tkonno/epics-base
export PATH=${EPICS_HOME}/bin/linux-x86_64:${PATH}
