#!/bin/bash

# Edit path to your root setup
source ${HOME}/root/bin/thisroot.sh

export JSNS2_HOME=${PWD}
export PATH=${PWD}/bin:${PATH}
export LD_LIBRARY_PATH=${PWD}/lib:${LIBPATH}
export LIBPATH=${PWD}/lib:${LIBPATH}

